php:
    build: .
    working_dir: /var/www/app
    volumes:
        - /c/work:/var/www/app
        - /c/work/docker-apache-php-5.3-sqlserver/sites-enabled/:/etc/apache2/sites-enabled/
    ports:
        - 80:80
    environment:
        ENVIRONMENT: dev
        PHP_ERROR_REPORTING: E_ALL & ~E_NOTICE